on:
  push:
    branches:
      - master
  release:
    types:
      - published
name: build-publish
jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup env
        run: |
          SHA=${{ github.sha }}
          SHA=${SHA::7}
          echo SHA=$SHA >> $GITHUB_ENV
          IMAGE_TAG=$(basename $GITHUB_REF)
          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: build
        uses: project-stacker/stacker-build-push-action@main
        with:
          file: 'stacker.yaml'
          build-args: |
            KERNEL_URL=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
            KERNEL_BRANCH=linux-6.0.y
            REVISION=${{ env.SHA }}
            IMAGE_TAG=${{ env.IMAGE_TAG }}

  release:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup env
        run: |
          SHA=${{ github.sha }}
          SHA=${SHA::7}
          echo SHA=$SHA >> $GITHUB_ENV
          IMAGE_TAG=$(basename $GITHUB_REF)
          echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
      - name: build and push
        uses: project-stacker/stacker-build-push-action@main
        with:
          file: 'stacker.yaml'
          build-args: |
            KERNEL_URL=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
            KERNEL_BRANCH=linux-6.0.y
            REVISION=${{ env.SHA }}
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          url: docker://zothub.io/machine/kernel
          tags: ${{ env.IMAGE_TAG }}
          username: ${{ secrets.ZOTHUB_USERNAME }}
          password: ${{ secrets.ZOTHUB_PASSWORD }}
